[versions]
agp = "8.13.2"
fragmentTesting = "1.8.9"
fragmentTestingManifest = "1.8.9"
hiltAndroid = "2.57.1"
hiltCompiler = "2.57.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
navigationFragment = "2.9.7"
navigationUi = "2.9.7"
rules = "1.7.0"
runner = "1.7.0"

[libraries]
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragmentTesting" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
fragment-testing-manifest = { module = "androidx.fragment:fragment-testing-manifest", version.ref = "fragmentTestingManifest" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
rules = { module = "androidx.test:rules", version.ref = "rules" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

